language: node_js

node_js:
  - 12.14.1

notifications:
  - email: false

services:
  - postgresql

before_script:
  - psql -c 'create database politico_travis;' -U postgres

script: 
  - npm run drop-tables && npm run create-tables && nyc mocha --require @babel/register ./server/tests/ --exit && nyc report --reporter=text-lcov | coveralls