language: node_js

node_js:
  - 12.14.1

notifications:
  - email: false

script: set NODE_ENV=test&& npm run drop-tables && npm run create-tables && nyc mocha --require @babel/register ./server/tests/ --exit
